baseURL = 'https://donghuabatch.com/'
title = 'DonghuaBatch - Tempatnya Download Batch Donghua Subtitle Indonesia'
defaultContentLanguage = 'id'

preserveTaxonomyNames = true

[services]
    [services.googleAnalytics]
        id = 'G-7B40JB824Z'
    [services.rss]
        limit = -1

[taxonomies]
    genres = 'genre'
    studios = 'studio'
    seasons = 'season'

[markup.goldmark.renderer]
    unsafe = true

[params]
    deskripsi = 'Tempat Download Batch Donghua subtitle Indonesia'
    keywords = 'Donghua, Batch, Subtitle Indonesia'
    author = 'Admin'
    img = '/img/favicon.webp'

[sitemap]
    changeFreq = 'weekly'
    priority = 0.8

[outputs]
    home = ['HTML', 'rss', 'json']