baseURL = 'https://mydonghua.syukra.org/'
title = 'MyDonghua - Tempatnya Download Batch Donghua Subtitle Indonesia Terlengkap'
defaultContentLanguage = 'id'

[services]
    [services.googleAnalytics]
        id = 'G-99GNVNF3VY'
    [services.rss]
        limit = -1

[taxonomies]
    genres = 'genre'
    studios = 'studio'
    seasons = 'season'

[markup.goldmark.renderer]
    unsafe = true

[params]
    deskripsi = 'Tempat Download Batch Donghua terlengkap subtitle Indonesia'
    keywords = 'Donghua, Batch, Subtitle Indonesia'
    author = 'Admin'

[sitemap]
    changeFreq = 'weekly'

[outputs]
    home = ['HTML', 'rss']
    taxonomy = ['html']